Create леонид_все_ещё_пидор
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required. 
В общем и целом код работает, но не работает (ошибка выше)